# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goods_font_image',
            new_name='goods_front_image',
        ),
    ]
